# Generated by Django 4.2.7 on 2025-12-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("device_management", "0002_alter_device_certificate_serial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("data", models.JSONField(default=dict)),
                ("recieved_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "certificate_serial",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="device_management.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Message",
                "verbose_name_plural": "Device Messages",
                "ordering": ["-recieved_at"],
            },
        ),
    ]
