# Generated by Django 4.2.7 on 2026-02-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_processing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("device_management", "0008_deviceauditentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("DETECTION_RATE_SPIKE", "Detection Rate Spike"),
                            ("SILENT_DEVICE", "Silent Device"),
                            ("AUTH_UNKNOWN_IP", "Authentication from Unknown IP"),
                            ("AUTH_MALFORMED_MESSAGE", "Malformed Message Received"),
                        ],
                        help_text="Type of anomaly detected",
                        max_length=40,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Severity level of the anomaly",
                        max_length=10,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Plain-English description of why this flag was raised"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Supporting data used to generate the flag (for admin investigation)",
                    ),
                ),
                ("raised_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the admin marked this flag as resolved",
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Device associated with this anomaly (null for network-wide flags)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomaly_flags",
                        to="device_management.device",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who resolved this flag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Flag",
                "verbose_name_plural": "Anomaly Flags",
                "ordering": ["-raised_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptive title for the incident",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what is being investigated",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Overall severity of the incident",
                        max_length=10,
                    ),
                ),
                (
                    "incident_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Under Investigation"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated"),
                        ],
                        default="OPEN",
                        help_text="Current investigation status",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who created this incident",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_flags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Anomaly flags associated with this incident",
                        related_name="incidents",
                        to="anomaly_detection.anomalyflag",
                    ),
                ),
                (
                    "linked_messages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Detection events associated with this incident",
                        related_name="incidents",
                        to="data_processing.devicemessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Free-text investigation note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Admin who wrote this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        help_text="Incident this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="anomaly_detection.incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Note",
                "verbose_name_plural": "Incident Notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceIPHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address the device was seen from"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="First time this device was seen from this IP",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Most recent time this device was seen from this IP",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device that communicated from this IP",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_history",
                        to="device_management.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device IP History",
                "verbose_name_plural": "Device IP Histories",
                "unique_together": {("device", "ip_address")},
            },
        ),
    ]
