# Generated by Django 4.2.7 on 2026-02-28 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0009_devicecommand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anomaly_detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SET_INTERVAL", "Change reporting interval"),
                            ("SET_THRESHOLD", "Change detection threshold"),
                            ("REBOOT", "Reboot device"),
                        ],
                        help_text="Command action to execute on the device",
                        max_length=32,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action parameters (e.g. {'seconds': 60} for SET_INTERVAL)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending delivery"),
                            ("DELIVERED", "Delivered to device"),
                            ("ACKNOWLEDGED", "Acknowledged by device"),
                            ("EXPIRED", "Expired undelivered"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current delivery status",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the command was included in a message response",
                        null=True,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the device confirmed execution",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Command is discarded undelivered after this time (null = never)",
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Target device for this command",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="device_management.device",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who dispatched this command (null = system/policy)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Command",
                "verbose_name_plural": "Device Commands",
                "ordering": ["-created_at"],
            },
        ),
    ]
