# Generated by Django 4.2.7 on 2026-03-01 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("device_management", "0009_devicecommand"),
        ("anomaly_detection", "0002_devicecommand"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short descriptive name for this policy",
                        max_length=128,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer explanation of what this policy does",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive policies are never evaluated",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE_RATE_HIGH", "Message rate above threshold"),
                            (
                                "MESSAGE_RATE_LOW",
                                "Message rate below threshold (silence)",
                            ),
                            ("CERT_EXPIRY_SOON", "Certificate expiring within N days"),
                            (
                                "NO_MESSAGES_EVER",
                                "Device registered but never sent a message",
                            ),
                            (
                                "MESSAGE_TYPE_RATIO",
                                "Detection-type message ratio above threshold",
                            ),
                        ],
                        help_text="What to measure",
                        max_length=32,
                    ),
                ),
                (
                    "threshold_value",
                    models.FloatField(
                        help_text="Numeric threshold: message count (RATE), days (CERT_EXPIRY_SOON / NO_MESSAGES_EVER), or percentage 0-100 (MESSAGE_TYPE_RATIO)"
                    ),
                ),
                (
                    "window_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Evaluation window in minutes (ignored for CERT_EXPIRY_SOON and NO_MESSAGES_EVER)",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FLAG_ANOMALY", "Raise anomaly flag"),
                            ("QUEUE_COMMAND", "Queue device command"),
                            ("CHANGE_STATUS", "Change device status"),
                            ("CREATE_INCIDENT", "Open incident and link flag"),
                        ],
                        help_text="What to do when condition is met",
                        max_length=32,
                    ),
                ),
                (
                    "action_severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Severity for FLAG_ANOMALY / CREATE_INCIDENT actions",
                        max_length=16,
                    ),
                ),
                (
                    "action_command",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SET_INTERVAL", "Change reporting interval"),
                            ("SET_THRESHOLD", "Change detection threshold"),
                            ("REBOOT", "Reboot device"),
                        ],
                        help_text="Command to queue for QUEUE_COMMAND action",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "action_command_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Params for the queued command (e.g. {'seconds': 60})",
                    ),
                ),
                (
                    "action_device_status",
                    models.CharField(
                        blank=True,
                        help_text="Target device status for CHANGE_STATUS action",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit to a single device (takes precedence over applies_to_type)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="device_management.device",
                    ),
                ),
                (
                    "applies_to_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit to devices of this type (null = all types)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies",
                        to="device_management.devicetype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Policy",
                "verbose_name_plural": "Detection Policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="anomalyflag",
            name="flag_type",
            field=models.CharField(
                choices=[
                    ("DETECTION_RATE_SPIKE", "Detection Rate Spike"),
                    ("SILENT_DEVICE", "Silent Device"),
                    ("AUTH_UNKNOWN_IP", "Authentication from Unknown IP"),
                    ("AUTH_MALFORMED_MESSAGE", "Malformed Message Received"),
                    ("POLICY_TRIGGERED", "Policy Rule Triggered"),
                ],
                help_text="Type of anomaly detected",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PolicyTriggerLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "detail",
                    models.JSONField(
                        default=dict,
                        help_text="Measured value, threshold, and action taken at trigger time",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_triggers",
                        to="device_management.device",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_logs",
                        to="anomaly_detection.detectionpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Trigger Log",
                "verbose_name_plural": "Policy Trigger Logs",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
