# Generated by Django 4.2.7 on 2025-12-10 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for the device (e.g., 'Sensor-Vilnius-001')",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_serial",
                    models.BigIntegerField(
                        blank=True,
                        help_text="X.509 certificate serial number",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "certificate_expiry",
                    models.DateTimeField(
                        blank=True, help_text="Certificate expiration date", null=True
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        blank=True, help_text="PEM-encoded certificate", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-created_at"],
            },
        ),
    ]
