# Generated by Django 4.2.7 on 2025-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="certificate_serial",
            field=models.CharField(
                blank=True,
                help_text="X.509 certificate serial number (hex)",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
