# Generated by Django 4.2.7 on 2026-01-08 20:01

from django.db import migrations, models
import django.db.models.deletion


def set_existing_devices_inactive(apps, schema_editor):
    """
    Data migration: Set all existing devices without coordinates to INACTIVE status.
    This ensures devices created before location fields were added are clearly marked.
    """
    Device = apps.get_model('device_management', 'Device')
    # Update devices that don't have coordinates (NULL latitude/longitude)
    updated_count = Device.objects.filter(latitude__isnull=True, longitude__isnull=True).update(status='INACTIVE')
    print(f"Set {updated_count} existing devices to INACTIVE status")


def reverse_inactive_status(apps, schema_editor):
    """
    Reverse migration: Set devices back to PENDING if they were changed to INACTIVE.
    This is a best-effort reversal - we can't know the original status.
    """
    Device = apps.get_model('device_management', 'Device')
    # Revert INACTIVE devices without coordinates back to PENDING
    Device.objects.filter(status='INACTIVE', latitude__isnull=True, longitude__isnull=True).update(status='PENDING')


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0002_alter_device_certificate_serial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type of device (e.g., 'Raspberry Pi', 'ESP8266')",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Type",
                "verbose_name_plural": "Device Types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="device",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description or notes about the device",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude coordinate (-90 to 90)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude coordinate (-180 to 180)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of IoT device",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="device_management.devicetype",
            ),
        ),
        # Data migration: mark existing devices without coordinates as INACTIVE
        migrations.RunPython(set_existing_devices_inactive, reverse_inactive_status),
    ]
