# Generated by Django 4.2.7 on 2026-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "device_management",
            "0003_devicetype_device_description_device_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="certificate_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when certificate was generated (for 24-hour download window)",
                null=True,
            ),
        ),
    ]
