# Generated by Django 4.2.7 on 2026-01-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0004_device_certificate_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="private_key_pem",
            field=models.TextField(
                blank=True,
                help_text="PEM-encoded private key (stored temporarily for 24-hour download window)",
                null=True,
            ),
        ),
    ]
