# Generated by Django 4.2.7 on 2026-01-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0006_device_certificate_algorithm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="certificate_algorithm",
            field=models.CharField(
                choices=[
                    ("ECDSA_P256", "ECDSA P-256 (secp256r1)"),
                    ("ECDSA_P384", "ECDSA P-384 (secp384r1)"),
                    ("RSA_2048", "RSA-2048"),
                    ("RSA_4096", "RSA-4096"),
                ],
                default="ECDSA_P384",
                help_text="Cryptographic algorithm for device certificate (choose ECDSA for resource-constrained devices)",
                max_length=20,
            ),
        ),
    ]
