# Generated by Django 4.2.7 on 2026-02-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("device_management", "0007_alter_device_certificate_algorithm"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceAuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DEVICE_REGISTERED", "Device Registered"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("CERTIFICATE_GENERATED", "Certificate Generated"),
                            ("CERTIFICATE_DOWNLOADED", "Certificate Downloaded"),
                            ("ANOMALY_RAISED", "Anomaly Flag Raised"),
                            ("ANOMALY_RESOLVED", "Anomaly Flag Resolved"),
                            ("DEVICE_UPDATED", "Device Details Updated"),
                        ],
                        help_text="Category of event",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what happened"
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured context for the event",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device this entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="device_management.device",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the event (null if triggered automatically)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Audit Entry",
                "verbose_name_plural": "Device Audit Entries",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
