# Generated by Django 4.2.7 on 2026-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0008_deviceauditentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceauditentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DEVICE_REGISTERED", "Device Registered"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("CERTIFICATE_GENERATED", "Certificate Generated"),
                    ("CERTIFICATE_DOWNLOADED", "Certificate Downloaded"),
                    ("ANOMALY_RAISED", "Anomaly Flag Raised"),
                    ("ANOMALY_RESOLVED", "Anomaly Flag Resolved"),
                    ("DEVICE_UPDATED", "Device Details Updated"),
                    ("COMMAND_DISPATCHED", "Command Dispatched"),
                    ("COMMAND_ACKNOWLEDGED", "Command Acknowledged"),
                ],
                help_text="Category of event",
                max_length=30,
            ),
        ),
    ]
